name: Daily Trading Sequence

on:
  workflow_dispatch: {}

concurrency:
  group: daily-trading-sequence
  cancel-in-progress: false

jobs:
  run-trading-sequence:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # Configure these secrets in your repository settings -> Secrets
      GROQ_API_KEY_1: ${{ secrets.GROQ_API_KEY_1 }}
      GROQ_API_KEY_2: ${{ secrets.GROQ_API_KEY_2 }}
      AI_MODEL_NAME_1: ${{ secrets.AI_MODEL_NAME_1 }}
      AI_MODEL_NAME_2: ${{ secrets.AI_MODEL_NAME_2 }}
      TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PDF_RETENTION_DAYS: ${{ secrets.PDF_RETENTION_DAYS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release xdg-utils

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
        run: sudo npm install --no-package-lock

      - name: Run trading_sequence.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
        run: node trading_sequence.js
