name: Daily Trading Sequence

on:
  workflow_dispatch: {}

concurrency:
  group: daily-trading-sequence
  cancel-in-progress: false

jobs:
  run-trading-sequence:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # Configure these secrets in your repository settings -> Secrets
      GROQ_API_KEY_1: ${{ secrets.GROQ_API_KEY_1 }}
      GROQ_API_KEY_2: ${{ secrets.GROQ_API_KEY_2 }}
      AI_MODEL_NAME_1: ${{ secrets.AI_MODEL_NAME_1 }}
      AI_MODEL_NAME_2: ${{ secrets.AI_MODEL_NAME_2 }}
      TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PDF_RETENTION_DAYS: ${{ secrets.PDF_RETENTION_DAYS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Puppeteer system dependencies (Linux runners)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libatk-bridge2.0-0 libgtk-3-0 libgbm1 libnss3 libxss1 libasound2t64 chromium-browser chromium

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        run: sudonpm install --no-package-lock # Changed from npm ci to npm install with --no-package-lock flag

      - name: Run trading_sequence.js
        run: node trading_sequence.js
